image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
      flutter precache
      flutter pub get
    command: |
      flutter run -d chrome

ports:
  - port: 5000
    onOpen: open-preview
