// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdgkX3kHY-xvXg8npPfkF1Nuhn_t6x_1E',
    appId: '1:565177201642:web:2e65f7c82f47eeeb20f893',
    messagingSenderId: '565177201642',
    projectId: 'flutter-notes-app-6dae4',
    authDomain: 'flutter-notes-app-6dae4.firebaseapp.com',
    storageBucket: 'flutter-notes-app-6dae4.firebasestorage.app',
    measurementId: 'G-PV29ZRMC0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp3v7YsgUy23I23ocgG2DZIPKjsAKeoQQ',
    appId: '1:565177201642:android:730877a2b071e05920f893',
    messagingSenderId: '565177201642',
    projectId: 'flutter-notes-app-6dae4',
    storageBucket: 'flutter-notes-app-6dae4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU29Kk9B_6d2GR32Pxn8EBAj_yslBZwj0',
    appId: '1:565177201642:ios:ce6c84a8eed0b72a20f893',
    messagingSenderId: '565177201642',
    projectId: 'flutter-notes-app-6dae4',
    storageBucket: 'flutter-notes-app-6dae4.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU29Kk9B_6d2GR32Pxn8EBAj_yslBZwj0',
    appId: '1:565177201642:ios:ce6c84a8eed0b72a20f893',
    messagingSenderId: '565177201642',
    projectId: 'flutter-notes-app-6dae4',
    storageBucket: 'flutter-notes-app-6dae4.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdgkX3kHY-xvXg8npPfkF1Nuhn_t6x_1E',
    appId: '1:565177201642:web:f493834fff3f3b1020f893',
    messagingSenderId: '565177201642',
    projectId: 'flutter-notes-app-6dae4',
    authDomain: 'flutter-notes-app-6dae4.firebaseapp.com',
    storageBucket: 'flutter-notes-app-6dae4.firebasestorage.app',
    measurementId: 'G-D91FMCWH0H',
  );
}